### ISSUE TITLE
엔티티 매핑 작업

### ISSUE THREAD

**Issue by nsnnsn12** [nsnnsn12/pr2s#6]
#### Description
ERD를 기반으로 엔티티를 매핑한다.
파트 배분
현우 = {방정보, 예약, 즐겨찾기, 파일}
나현 = {기관, 댓글, 담당자, 가입기관정보, 방사진}
동민 = {공통코드종류, 공통코드, 게시판, 게시글, 주소}
성규 = {사용자}

#### Tasks
- [x] 현우
- [x] 나현
- [x] 동민
- [x] 성규

#### TODO
- [x] File 엔티티 객체 매핑 필요 -> relation issue number : #6

**Comment by nahyunoh** [comment]
todo

- [ ] File 엔티티 객체 매핑 필요

**Comment by HyunWooParkKEIG** [comment]
//// TODO: 2022-06-16 File 매핑작업 필요
